### ISSUE TITLE
require("lru-cache") doesn't work in the cjs dist

### ISSUE THREAD

**Issue by aminya** [isaacs/path-walker#10]
`lru_cache_1` here itself is the class.

```js
/home/aminya/setup-cpp/node_modules/.pnpm/path-scurry@1.7.0/node_modules/path-scurry/dist/cjs/index.js:131
class ResolveCache extends lru_cache_1.LRUCache {
                                       ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/aminya/setup-cpp/node_modules/.pnpm/path-scurry@1.7.0/node_modules/path-scurry/dist/cjs/index.js:131:40)
```

**Comment by isaacs** [comment]
If that's the case, then you are getting the wrong version of LRUCache.  `lru-cache` started using a named export instead of a default export in version 9.  `path-scurry` requires `lru-cache@^9.0.0`.

It looks like you're using pnpm, which I'm not an expert on.  But I believe you can inspect the version in `node_modules/.pnpm/path-scurry@1.7.0/node_modules/lru-cache/package.json` to verify.

**Comment by aminya** [comment]
I had overridden the version for LRU cache. That's why this happened. It would be nice to update the lru-cache dependency.

**Comment by isaacs** [comment]
It already depends on the version it needs. If you override deps, it can break stuff, that's just the power that comes with that tool. 🤷
