### ISSUE TITLE
lstat failure due to wrong directory

### ISSUE THREAD

**Issue by atomicpages** [isaacs/path-walker#24]
Hey there, big fan of your projects. I'm using `glob` to find files and I'm seeing a really strange issue where `lstat` is looking at the wrong directory. I'm not doing any crazy customization with glob and directory exist before `glob` runs so there's no obvious risk of stat caching:

```ts
// paths guaranteed to exist by the time these variables are created
const root = `${os.homedir()}/some-lib/packages/icons-jsx`;
const cwd = "src";

// ...
const esm = await glob("**/index.{mjs,d.mts}", { cwd, root });
// do something with esm
```

As the files get resolved I'm seeing an error referencing something other than my `root` and `cwd`:

```txt
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, access 'dist'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: 'dist'
}
```

I narrowed it down to this line:

https://github.com/isaacs/path-scurry/blob/021f142cdbac4183154cfc3c5c1e8db836a87f79/src/index.ts#L1073

I added a `console.log` in the code to monitor the result of `this.fullPath()` and it's 100% correct so I'm not sure how `dist` is coming into the picture. Has anyone encountered this issue before?

**Comment by isaacs** [comment]
Thanks for the kind words.

This is pretty confusing!

The only thing I can think of that might be at all connected to `dist` nearby those modules is the `glob` bin's use of `package-json-from-dist`. But I don't see how that would be related.

Do you have a full example that fails? Or can you tell me anything else about the file system and how to reproduce it? It's also very strange for that to raise an error that fails the promise, because the line you reference is wrapped in a try/catch already. When `Path.lstat()` fails, it just marks the entry as not existing, and returns undefined.

**Comment by atomicpages** [comment]
Welcome! Oddly enough, I think was an issue with node/bun conflicting with each other. I disabled the bun plugin on VSCode and things started behaving as expected 🤷 super strange
